hash-format = "sha256"

[[files]]
file = "mods/fabric-api.toml"
hash = "05f054965d0aab61ddf3569fad49fd3ffb8d922c82fb0ec5d4f5cfb72679309f"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "735bb894e8fd0430de8fe331347ff24c5c64643bc65f2c040f7a82fb17e8b826"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "219d4425679c60fd2855a6a39a6fccb6db3948dcc57b9da7c20907c855c5bd3d"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "8243fcb2221942db16259a029d2964ca41d7a336fccc60464597d9f0d6699529"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "722031c0ae5d2de71783d6c4bfbf1c5cd25c65e55cb42d8bb4f7cadf478c4368"
metafile = true
